- hosts: all
  tasks:
    - name: put home on local NVMe
      shell: |
         DEVNAME=`realpath /dev/disk/by-id/nvme-Amazon_EC2_NVMe_Instance_Storage*|head -1`
         if [ ! -b "${DEVNAME}" ]; then exit 0; fi
         if `mount|grep -q "${DEVNAME}"`; then exit 0; fi
         sudo mkfs.ext4 "${DEVNAME}"
         sudo mkdir /data0
         sudo mount "${DEVNAME}" /data0
         sudo bash -c "echo '${DEVNAME} /data0 ext4 defaults 0 1' >> /etc/fstab"
         sudo mkdir /data0/ubuntu
         sudo chown ubuntu:ubuntu /data0/ubuntu
         rsync -a ~/ /data0/ubuntu/
         cd $HOME
         cd ..
         HOMEP=`pwd -P`
         # variable substitution happens in the shell before the sudo
         sudo mv "${HOME}" "${HOME}.old"
         sudo bash -c "cd ${HOMEP}; ln -s /data0/ubuntu ${USER}"

      no_log: False
      args:
        executable: /bin/bash
