- hosts: all
  gather_facts: no
  vars:
    CLOUDFLARE_ZONE_ID:    "{{ lookup('env','CLOUDFLARE_ZONE_ID') }}"
    CLOUDFLARE_EMAIL:      "{{ lookup('env','CLOUDFLARE_EMAIL') }}"
    CLOUDFLARE_AUTH_KEY:   "{{ lookup('env','CLOUDFLARE_AUTH_KEY') }}"
    AWS_ACCESS_KEY_ID:     "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    S3_RELEASE_BUCKET:     "{{ lookup('env','S3_RELEASE_BUCKET') }}"
  tasks:
    - fail:
        msg: Some of the AWS variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_RELEASE_BUCKET are undefined
      when: (AWS_ACCESS_KEY_ID|length == 0) or (AWS_SECRET_ACCESS_KEY|length == 0) or (S3_RELEASE_BUCKET|length == 0)
    - name: Run initial Installation and nodecfg provisioning for all Hosts
      shell: |
         export CLOUDFLARE_ZONE_ID={{ CLOUDFLARE_ZONE_ID|quote }}
         export CLOUDFLARE_EMAIL={{ CLOUDFLARE_EMAIL|quote }}
         export CLOUDFLARE_AUTH_KEY={{ CLOUDFLARE_AUTH_KEY|quote }}
         export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID|quote }}
         export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY|quote }}
         export S3_RELEASE_BUCKET={{ S3_RELEASE_BUCKET|quote }}

         source ~/_algonet/environment/identity

         echo "Network $NETWORK"

         cd ~
         (pkill algod; pkill algoh; pkill kmd; pkill node_exporter) || true
         rm -rf algorand .algorand

         cd ~/installer
         ./update.sh -i -c $CHANNEL -p ~/algorand/${NETWORK} -b algorand-releases -d ~/tmp/_tmp -n
         rm -rf ~/tmp/_tmp

         ~/algorand/${NETWORK}/updater gettools -c $CHANNEL -o tools.tar.gz -b algorand-releases
         tar -xf tools.tar.gz -C ~/algorand/${NETWORK}

         cd ~/algorand/${NETWORK}
         ./nodecfg apply -c spectest -H "${NODECFGHOST}" -a "${HOSTADDRESS}" -n . -b algorand-internal

      no_log: False
      args:
        executable: /bin/bash
