- hosts: all
  tasks:
    - name: Resets all Algorand Nodes to pre-install state - ready to `algonet play update`
      shell: |
         source ~/_algonet/environment/identity
         cd ~/algorand/${NETWORK}
         ./goal node stop $(./find-nodes.sh data)
         (pkill algod; pkill algoh; pkill kmd; pkill node_exporter) || true
         cd ~
         rm -rf algorand .algorand

      no_log: False
      args:
        executable: /bin/bash
